version: "3"

services:
  # api:
  #   container_name: github_actions_nest
  #   build:
  #     context: ./nest
  #     dockerfile: Dockerfile.dev
  #   tty: true
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - "./nest:/nest"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #   depends_on:
  #     - db
  #   command: "yarn start:dev"

  front:
    container_name: github_actions_next
    build:
      context: ./next
      dockerfile: Dockerfile.dev
    volumes:
      - ./next:/next
    tty: true
    ports:
      - 8080:8080
    # depends_on:
    #   - api
